language: ruby
rvm:
  - 1.9.2
  - 1.9.3
before_script:
  - psql -c 'create database listenlater_test;' -U postgres
  - "cp config/database.yml.travis config/database.yml"
  - bundle exec rake db:test:prepare
